up:
	tinet up -c tinet.yaml | sudo sh -x

login:
	docker exec -it BGPRouter1 /bin/bash

login2:
	docker exec -it BGPRouter2 /bin/bash

conf:
	tinet conf -c tinet.yaml | sudo sh -x

down:
	tinet down -c tinet.yaml | sudo sh -x

